version: '3.1'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgresql:
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "psql -U test -l"]
      interval: 10s
      timeout: 5s
      retries: 5
